### GET products
GET http://localhost:5000/products
Accept: application/json


### POST Create new Product
POST http://localhost:5000/products
Content-Type: application/json

{
  "name": "Product A",
  "kind": "unknown"
}


### GET product
GET http://localhost:5000/products/323fa691-f799-45b3-8f89-4b1c8ed017e8
Accept: application/json


### DELETE product
DELETE http://localhost:5000/products/323fa691-f799-45b3-8f89-4b1c8ed017e8
Accept: application/json
